//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementWEBjm.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Henkilot3
    {
        public int Henkilot_id { get; set; }
        public string Etunimi { get; set; }
        public string Esimies { get; set; }
    }
}
