//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementWEBjm.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projektit3
    {
        public int Projekti_id { get; set; }
        public string Nimi { get; set; }
        public string Esimies { get; set; }
        public Nullable<System.DateTime> Avattu { get; set; }
        public Nullable<int> projectstate { get; set; }
    }
}
